name: qa4sm_preprocessing
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aws-c-auth=0.7.3
  - aws-c-cal=0.6.2
  - aws-c-common=0.9.0
  - aws-c-compression=0.2.17
  - aws-c-event-stream=0.3.2
  - aws-c-http=0.7.12
  - aws-c-io=0.13.32
  - aws-c-mqtt=0.9.6
  - aws-c-s3=0.3.17
  - aws-c-sdkutils=0.1.12
  - aws-checksums=0.1.17
  - aws-crt-cpp=0.23.1
  - aws-sdk-cpp=1.11.156
  - blas=1.0
  - bokeh=2.4.3
  - bottleneck=1.3.5
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.08.22
  - certifi=2023.7.22
  - cftime=1.6.2
  - charset-normalizer=3.2.0
  - click=8.0.4
  - cloudpickle=2.2.1
  - configobj=5.0.6
  - cytoolz=0.12.0
  - dask=2023.5.0
  - dask-core=2023.5.0
  - distributed=2023.5.0
  - freetype=2.12.1
  - fsspec=2023.9.2
  - geos=3.8.0
  - gflags=2.2.2
  - giflib=5.2.1
  - glog=0.6.0
  - hdf4=4.2.13
  - hdf5=1.12.1
  - heapdict=1.0.1
  - idna=3.4
  - importlib-metadata=6.0.0
  - importlib_metadata=6.0.0
  - intel-openmp=2023.1.0
  - jinja2=3.1.2
  - jpeg=9e
  - krb5=1.20.1
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libabseil=20230802.1
  - libarrow=13.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.2.1
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=13.2.0
  - libgoogle-cloud=2.12.0
  - libgrpc=1.57.0
  - liblapack=3.9.0
  - libnetcdf=4.8.1
  - libnghttp2=1.52.0
  - libnuma=2.0.16
  - libpng=1.6.39
  - libprotobuf=4.23.4
  - libssh2=1.10.0
  - libstdcxx-ng=13.2.0
  - libthrift=0.19.0
  - libtiff=4.5.1
  - libutf8proc=2.8.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libzip=1.8.0
  - libzlib=1.2.13
  - locket=1.0.0
  - lz4=4.3.2
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - msgpack-python=1.0.3
  - ncurses=6.4
  - netcdf4=1.5.7
  - numexpr=2.8.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openssl=3.1.3
  - orc=1.9.0
  - packaging=23.1
  - pandas=1.5.3
  - partd=1.4.0
  - pillow=9.4.0
  - pip=23.2.1
  - platformdirs=2.6.0
  - pooch=1.7.0
  - proj=8.2.1
  - psutil=5.9.0
  - pyarrow=13.0.0
  - pykdtree=1.3.4
  - pyproj=3.4.1
  - pyresample=1.26.1
  - pysocks=1.7.1
  - python=3.8.18
  - python-dateutil=2.8.2
  - python-lmdb=1.4.1
  - python-tzdata=2023.3
  - python_abi=3.8
  - pytz=2023.3.post1
  - pyyaml=6.0
  - rdma-core=28.9
  - re2=2023.03.02
  - readline=8.2
  - requests=2.31.0
  - s2n=1.3.51
  - scipy=1.10.1
  - setuptools=68.0.0
  - shapely=2.0.1
  - six=1.16.0
  - snappy=1.1.10
  - sortedcontainers=2.4.0
  - sqlite=3.41.2
  - tbb=2021.8.0
  - tblib=1.7.0
  - tk=8.6.12
  - toolz=0.12.0
  - tornado=6.3.2
  - typing_extensions=4.7.1
  - ucx=1.14.1
  - urllib3=2.0.3
  - wheel=0.41.2
  - xarray=2022.11.0
  - xz=5.4.2
  - yaml=0.2.5
  - zict=2.2.0
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - asciitree==0.3.3
      - cf-xarray==0.8.4
      - contourpy==1.1.1
      - coverage==7.3.1
      - cycler==0.11.0
      - entrypoints==0.4
      - exceptiongroup==1.1.3
      - fasteners==0.19
      - fonttools==4.42.1
      - h5py==3.9.0
      - importlib-resources==6.1.0
      - iniconfig==2.0.0
      - kiwisolver==1.4.5
      - matplotlib==3.7.3
      - more-itertools==10.1.0
      - numcodecs==0.11.0
      - parse==1.19.1
      - pluggy==1.3.0
      - pygeobase==0.6.2
      - pygeogrids==0.4.2
      - pynetcf==0.5.0
      - pyparsing==3.1.1
      - pytest==7.4.2
      - pytest-cov==4.1.0
      - repurpose==0.12
      - tomli==2.0.1
      - tqdm==4.66.1
      - trollsift==0.5.0
      - zarr==2.16.1
      - sphinx_rtd_theme
      - chardet
