name: qa4sm_preprocessing_docs
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas
  - numpy
  - netcdf4
  - pyresample
  - gdal
  - geos
  - matplotlib
  - cartopy
  - jupyterlab
  - xarray
  - dask
  - pip
  - pip:
      - pygeobase
      - parse
      - pygeogrids
      - pynetcf
      - repurpose
      - trollsift
      - cadati
      - smecv_grid
      - rasterio
      - ipywidgets
      - ismn
      - git+https://github.com/wpreimes/io_utils@v0.1
      - numba
      - pytesmo
      - pytest-cov
      - pytest
      - tqdm
      - sphinx_rtd_theme
      - nbsphinx